### ISSUE TITLE
Once log-in successful, re-route to front-end.

### ISSUE THREAD

**Issue by writetoalexander** [Danger-Will-Robinson/mariner#41]
Assigning to Joe for the time being. Feel free to re-assign if necessary. I feel this should be handled by Joe or Sean, since there are issues with logging into my youtube

**Comment by ph8tel** [comment]
On it!

**Comment by ph8tel** [comment]
Currently routing to ```res.redirect(`http://localhost:5000/reactTest`)``` after log in.
