### ISSUE TITLE
research api calls

### ISSUE THREAD

**Issue by writetoalexander** [Danger-Will-Robinson/mariner#55]

**Comment by writetoalexander** [comment]
Joe. Assigning this to you. But i would also like to get in on it. Hit me up on slack if you are feeling up for a research breakdown. Thanks!

**Comment by ph8tel** [comment]
OAuth part of twiter login is done! Now comes the API calls. Yaay!! We are all set to tackle this tomorrow. If you want to see how the OAuth part works, each step is detailed in the project.
